env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
    - make lint
builds:
- env:
    - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
    - arm
    - arm64
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: MacOS
      linux: Linux
      windows: Windows
      amd64: x86_64
    format_overrides:
    - goos: windows
      format: zip
    files:
      - LICENSE
      - README.md
      - mru-cables.toml.dist